version: '3'

volumes:
  postgres_data:
      driver: local

services:
  postgres:
      image: postgres
      volumes:
        - postgres_data:/var/lib/postgresql/data
      environment:
        POSTGRES_DB: linkedin
        POSTGRES_USER: smss
        POSTGRES_PASSWORD: ssaptonllahsuoy
#      ports:
#        - 5432:5432
      network_mode: "host"
#  prometheus:
#    image: prom/prometheus:v2.21.0
#    network_mode: "host"
#    #    ports:
#    #      - 9000:9090
#    volumes:
#      - ./prometheus:/etc/prometheus
#      - prometheus-data:/prometheus
#    container_name: "prom"
#  grafana:
#    image: grafana/grafana:7.5.7
#    network_mode: "host"
##    ports:
##      - 3000:3000
#    restart: unless-stopped
#    volumes:
#      - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
#      - grafana-data:/var/lib/grafana
#    container_name: "grafana"
